### PR TITLE
use IBM Plex font site-wide by default

### PR DESCRIPTION
**Pull request by isc-rsingh**
use IBM Plex font site-wide by default

### CODE REVIEW

**Comment by bradnoble** [comment]
I'm +1 on moving to the IBM font. But I want to make sure that we don't have any CSS collisions. I know that Materialize defaults to Roboto, and we have some CSS that specifies Helvetica in our exhibit.css. How should we scrub out conflicts / collisions?

cc @vabarbosa

**Comment by vabarbosa** [comment]
+1 from me too.

correct materializecss uses Roboto as default but you can [override/change it](http://materializecss.com/typography.html).

the `Helvetica Neue` font is currently being used for the **Search** and **Team** pages which can and probably should be replaced with IBM Plex.

**Review by vabarbosa — COMMENTED** [review]
@rajrsingh @bradnoble are we allowed to download and include it directly from our repo? if so, should we do that rather than from `1.www.s81c.com`. also, if concerned about IE (< 9), `*.eot` format should also be included.

**Comment by isc-rsingh** [comment]
@bradnoble @vabarbosa sorry for the delay. I can't find any reason why we shouldn't download and include directly. https://www.ibm.com/innovate/brand/typography/ says in multiple places, "IBM Plex should be used for all typographical situations, replacing Helvetica Neue, whenever possible".

Download here: https://ibm.ent.box.com/s/j90l2qhgjfysu6laq1rnt1anxspqxdcb?cm_mc_uid=11681343732915022084679&cm_mc_sid_50200000=1502483163

**Review by vabarbosa — APPROVED** [review]
👍

**Pull request merged**
